# Generated by Django 2.2 on 2020-02-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='create_time',
            new_name='create_date',
        ),
    ]
